// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.handypick.mimasu.host

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Basic environment facts, used to prove the channel round-trips before any
 * extension work is attempted.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HostInfo (
  val androidRelease: String,
  val sdkInt: Long,
  val hostPackage: String,
  /**
   * Whether the user has granted "install unknown apps" for this app.
   * Extension installs (INSTRUCTIONS.md 5.4) are impossible until this is true.
   */
  val canRequestPackageInstalls: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HostInfo {
      val androidRelease = pigeonVar_list[0] as String
      val sdkInt = pigeonVar_list[1] as Long
      val hostPackage = pigeonVar_list[2] as String
      val canRequestPackageInstalls = pigeonVar_list[3] as Boolean
      return HostInfo(androidRelease, sdkInt, hostPackage, canRequestPackageInstalls)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      androidRelease,
      sdkInt,
      hostPackage,
      canRequestPackageInstalls,
    )
  }
}

/**
 * An installed package that looks like it might be a Tachiyomi-family
 * extension. Deliberately unopinionated: the scan does not assume a feature
 * name or metadata key, it reports whatever the package actually declares so
 * the real values can be read off a device instead of guessed.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ExtensionCandidate (
  val packageName: String,
  val label: String,
  val versionName: String,
  val versionCode: Long,
  /** Absolute path of the installed APK, the input to PathClassLoader. */
  val apkPath: String,
  /** Every feature name the package declares in its manifest. */
  val features: List<String?>,
  /** Every application-level manifest metadata entry, stringified. */
  val metadata: Map<String?, String?>,
  /** SHA-256 of the signing certificate, uppercase hex, colon-separated. */
  val signatureSha256: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExtensionCandidate {
      val packageName = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val versionName = pigeonVar_list[2] as String
      val versionCode = pigeonVar_list[3] as Long
      val apkPath = pigeonVar_list[4] as String
      val features = pigeonVar_list[5] as List<String?>
      val metadata = pigeonVar_list[6] as Map<String?, String?>
      val signatureSha256 = pigeonVar_list[7] as String
      return ExtensionCandidate(packageName, label, versionName, versionCode, apkPath, features, metadata, signatureSha256)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      label,
      versionName,
      versionCode,
      apkPath,
      features,
      metadata,
      signatureSha256,
    )
  }
}

/**
 * A source instance the host managed to load, interrogated through the
 * shim interfaces.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LoadedSource (
  val className: String,
  val ok: Boolean,
  /** 64-bit, so carried as a string. */
  val sourceId: String,
  val name: String,
  val lang: String,
  val baseUrl: String,
  val supportsLatest: Boolean,
  val configurable: Boolean,
  /** How many filters the source declares for its search UI. */
  val filterCount: Long,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoadedSource {
      val className = pigeonVar_list[0] as String
      val ok = pigeonVar_list[1] as Boolean
      val sourceId = pigeonVar_list[2] as String
      val name = pigeonVar_list[3] as String
      val lang = pigeonVar_list[4] as String
      val baseUrl = pigeonVar_list[5] as String
      val supportsLatest = pigeonVar_list[6] as Boolean
      val configurable = pigeonVar_list[7] as Boolean
      val filterCount = pigeonVar_list[8] as Long
      val error = pigeonVar_list[9] as String?
      return LoadedSource(className, ok, sourceId, name, lang, baseUrl, supportsLatest, configurable, filterCount, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      className,
      ok,
      sourceId,
      name,
      lang,
      baseUrl,
      supportsLatest,
      configurable,
      filterCount,
      error,
    )
  }
}

/**
 * The result of attempting to load one class out of an extension APK.
 * Failures are values, not exceptions (INSTRUCTIONS.md 5.8).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ClassProbeResult (
  val className: String,
  /** Class.forName succeeded. */
  val loaded: Boolean,
  /**
   * A no-arg instance was constructed. Usually false until the
   * extensions-lib shim is present.
   */
  val instantiated: Boolean,
  /**
   * The class's ancestry and interfaces, which is how we discover the exact
   * extensions-lib type names an extension expects the host to provide.
   */
  val superclasses: List<String?>,
  /** Null when nothing went wrong. */
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClassProbeResult {
      val className = pigeonVar_list[0] as String
      val loaded = pigeonVar_list[1] as Boolean
      val instantiated = pigeonVar_list[2] as Boolean
      val superclasses = pigeonVar_list[3] as List<String?>
      val error = pigeonVar_list[4] as String?
      return ClassProbeResult(className, loaded, instantiated, superclasses, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      className,
      loaded,
      instantiated,
      superclasses,
      error,
    )
  }
}
private open class HostApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HostInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExtensionCandidate.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoadedSource.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClassProbeResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is HostInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ExtensionCandidate -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LoadedSource -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ClassProbeResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ExtensionHostApi {
  fun getHostInfo(): HostInfo
  /**
   * Scans installed packages and returns any whose declared features or
   * metadata keys contain one of [needles] (case-insensitive).
   * Pass something like ["tachiyomi", "aniyomi", "extension"].
   */
  fun scanForExtensions(needles: List<String?>): List<ExtensionCandidate?>
  /**
   * Whether the user has granted "install unknown apps" for this app.
   * Checked live rather than cached: the user can revoke it at any time.
   */
  fun canInstallPackages(): Boolean
  /**
   * Opens the system settings page where that grant is made. Returns false
   * if no such screen could be launched.
   */
  fun openInstallPermissionSettings(): Boolean
  /**
   * What a successfully loaded source reports about itself. Proves the host
   * can talk to an extension through the shim, not merely construct it.
   */
  fun loadSources(packageName: String, classNames: List<String?>): List<LoadedSource?>
  /**
   * Hosts an extension has contacted through the client the host provides.
   * Best-effort: an extension using its own client is not covered (5.7).
   */
  fun requestLogHostCounts(): Map<String?, Long?>
  /**
   * Builds a PathClassLoader over [packageName]'s APK and tries to load each
   * of [classNames], reporting ancestry and errors rather than throwing.
   */
  fun probeClasses(packageName: String, classNames: List<String?>): List<ClassProbeResult?>

  companion object {
    /** The codec used by ExtensionHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      HostApiPigeonCodec()
    }
    /** Sets up an instance of `ExtensionHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ExtensionHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.getHostInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getHostInfo())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.scanForExtensions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val needlesArg = args[0] as List<String?>
            val wrapped: List<Any?> = try {
              listOf(api.scanForExtensions(needlesArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.canInstallPackages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.canInstallPackages())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.openInstallPermissionSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openInstallPermissionSettings())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.loadSources$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val classNamesArg = args[1] as List<String?>
            val wrapped: List<Any?> = try {
              listOf(api.loadSources(packageNameArg, classNamesArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.requestLogHostCounts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.requestLogHostCounts())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.probeClasses$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val classNamesArg = args[1] as List<String?>
            val wrapped: List<Any?> = try {
              listOf(api.probeClasses(packageNameArg, classNamesArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
