// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.handypick.mimasu.host

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** How the catalogue is being asked for. */
enum class BrowseMode(val raw: Int) {
  POPULAR(0),
  LATEST(1),
  SEARCH(2);

  companion object {
    fun ofRaw(raw: Int): BrowseMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * What a download is doing. The host owns this, not Dart: a download outlives
 * the Flutter engine, so its state cannot live in a cubit.
 */
enum class DownloadState(val raw: Int) {
  QUEUED(0),
  RUNNING(1),
  COMPLETED(2),
  FAILED(3),
  CANCELLED(4);

  companion object {
    fun ofRaw(raw: Int): DownloadState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Why a download cannot be started right now. Distinguished from a failure
 * because nothing has gone wrong — the user asked at the wrong moment.
 */
enum class DownloadRefusal(val raw: Int) {
  NONE(0),
  METERED(1),
  UNSUPPORTED_FORMAT(2);

  companion object {
    fun ofRaw(raw: Int): DownloadRefusal? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Basic environment facts, used to prove the channel round-trips before any
 * extension work is attempted.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HostInfo (
  val androidRelease: String,
  val sdkInt: Long,
  val hostPackage: String,
  /**
   * Whether the user has granted "install unknown apps" for this app.
   * Extension installs (INSTRUCTIONS.md 5.4) are impossible until this is true.
   */
  val canRequestPackageInstalls: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HostInfo {
      val androidRelease = pigeonVar_list[0] as String
      val sdkInt = pigeonVar_list[1] as Long
      val hostPackage = pigeonVar_list[2] as String
      val canRequestPackageInstalls = pigeonVar_list[3] as Boolean
      return HostInfo(androidRelease, sdkInt, hostPackage, canRequestPackageInstalls)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      androidRelease,
      sdkInt,
      hostPackage,
      canRequestPackageInstalls,
    )
  }
}

/**
 * An installed package that looks like it might be a Tachiyomi-family
 * extension. Deliberately unopinionated: the scan does not assume a feature
 * name or metadata key, it reports whatever the package actually declares so
 * the real values can be read off a device instead of guessed.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ExtensionCandidate (
  val packageName: String,
  val label: String,
  val versionName: String,
  val versionCode: Long,
  /** Absolute path of the installed APK, the input to PathClassLoader. */
  val apkPath: String,
  /** Every feature name the package declares in its manifest. */
  val features: List<String?>,
  /** Every application-level manifest metadata entry, stringified. */
  val metadata: Map<String?, String?>,
  /** SHA-256 of the signing certificate, uppercase hex, colon-separated. */
  val signatureSha256: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExtensionCandidate {
      val packageName = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val versionName = pigeonVar_list[2] as String
      val versionCode = pigeonVar_list[3] as Long
      val apkPath = pigeonVar_list[4] as String
      val features = pigeonVar_list[5] as List<String?>
      val metadata = pigeonVar_list[6] as Map<String?, String?>
      val signatureSha256 = pigeonVar_list[7] as String
      return ExtensionCandidate(packageName, label, versionName, versionCode, apkPath, features, metadata, signatureSha256)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      label,
      versionName,
      versionCode,
      apkPath,
      features,
      metadata,
      signatureSha256,
    )
  }
}

/**
 * One title as an extension reported it.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FetchedAnime (
  val title: String,
  val url: String,
  val thumbnailUrl: String? = null,
  val description: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FetchedAnime {
      val title = pigeonVar_list[0] as String
      val url = pigeonVar_list[1] as String
      val thumbnailUrl = pigeonVar_list[2] as String?
      val description = pigeonVar_list[3] as String?
      return FetchedAnime(title, url, thumbnailUrl, description)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      url,
      thumbnailUrl,
      description,
    )
  }
}

/**
 * The outcome of asking a source for a page of titles.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FetchResult (
  val ok: Boolean,
  val sourceName: String,
  val items: List<FetchedAnime?>,
  val hasNextPage: Boolean,
  val millis: Long,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FetchResult {
      val ok = pigeonVar_list[0] as Boolean
      val sourceName = pigeonVar_list[1] as String
      val items = pigeonVar_list[2] as List<FetchedAnime?>
      val hasNextPage = pigeonVar_list[3] as Boolean
      val millis = pigeonVar_list[4] as Long
      val error = pigeonVar_list[5] as String?
      return FetchResult(ok, sourceName, items, hasNextPage, millis, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ok,
      sourceName,
      items,
      hasNextPage,
      millis,
      error,
    )
  }
}

/**
 * What an APK on disk declares about itself, read before installing.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ApkInfo (
  val ok: Boolean,
  val packageName: String,
  val label: String,
  val versionName: String,
  val versionCode: Long,
  /**
   * Lowercase hex, no separators, so it compares directly against the key a
   * repository index declares.
   */
  val signatureSha256: String,
  val features: List<String?>,
  val metadata: Map<String?, String?>,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApkInfo {
      val ok = pigeonVar_list[0] as Boolean
      val packageName = pigeonVar_list[1] as String
      val label = pigeonVar_list[2] as String
      val versionName = pigeonVar_list[3] as String
      val versionCode = pigeonVar_list[4] as Long
      val signatureSha256 = pigeonVar_list[5] as String
      val features = pigeonVar_list[6] as List<String?>
      val metadata = pigeonVar_list[7] as Map<String?, String?>
      val error = pigeonVar_list[8] as String?
      return ApkInfo(ok, packageName, label, versionName, versionCode, signatureSha256, features, metadata, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ok,
      packageName,
      label,
      versionName,
      versionCode,
      signatureSha256,
      features,
      metadata,
      error,
    )
  }
}

/**
 * A source instance the host managed to load, interrogated through the
 * shim interfaces.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LoadedSource (
  val className: String,
  val ok: Boolean,
  /** 64-bit, so carried as a string. */
  val sourceId: String,
  val name: String,
  val lang: String,
  val baseUrl: String,
  val supportsLatest: Boolean,
  val configurable: Boolean,
  /** How many filters the source declares for its search UI. */
  val filterCount: Long,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoadedSource {
      val className = pigeonVar_list[0] as String
      val ok = pigeonVar_list[1] as Boolean
      val sourceId = pigeonVar_list[2] as String
      val name = pigeonVar_list[3] as String
      val lang = pigeonVar_list[4] as String
      val baseUrl = pigeonVar_list[5] as String
      val supportsLatest = pigeonVar_list[6] as Boolean
      val configurable = pigeonVar_list[7] as Boolean
      val filterCount = pigeonVar_list[8] as Long
      val error = pigeonVar_list[9] as String?
      return LoadedSource(className, ok, sourceId, name, lang, baseUrl, supportsLatest, configurable, filterCount, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      className,
      ok,
      sourceId,
      name,
      lang,
      baseUrl,
      supportsLatest,
      configurable,
      filterCount,
      error,
    )
  }
}

/**
 * The result of attempting to load one class out of an extension APK.
 * Failures are values, not exceptions (INSTRUCTIONS.md 5.8).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ClassProbeResult (
  val className: String,
  /** Class.forName succeeded. */
  val loaded: Boolean,
  /**
   * A no-arg instance was constructed. Usually false until the
   * extensions-lib shim is present.
   */
  val instantiated: Boolean,
  /**
   * The class's ancestry and interfaces, which is how we discover the exact
   * extensions-lib type names an extension expects the host to provide.
   */
  val superclasses: List<String?>,
  /** Null when nothing went wrong. */
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ClassProbeResult {
      val className = pigeonVar_list[0] as String
      val loaded = pigeonVar_list[1] as Boolean
      val instantiated = pigeonVar_list[2] as Boolean
      val superclasses = pigeonVar_list[3] as List<String?>
      val error = pigeonVar_list[4] as String?
      return ClassProbeResult(className, loaded, instantiated, superclasses, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      className,
      loaded,
      instantiated,
      superclasses,
      error,
    )
  }
}

/**
 * One title as a source reported it. Only what `SAnime` carries: there is no
 * metadata service underneath, so this is all the app will ever know.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AnimeItem (
  val url: String,
  val title: String,
  val thumbnailUrl: String? = null,
  val description: String? = null,
  val author: String? = null,
  val genre: String? = null,
  /** SAnime's status constants: 0 unknown, 1 ongoing, 2 completed, and so on. */
  val status: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AnimeItem {
      val url = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val thumbnailUrl = pigeonVar_list[2] as String?
      val description = pigeonVar_list[3] as String?
      val author = pigeonVar_list[4] as String?
      val genre = pigeonVar_list[5] as String?
      val status = pigeonVar_list[6] as Long
      return AnimeItem(url, title, thumbnailUrl, description, author, genre, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      title,
      thumbnailUrl,
      description,
      author,
      genre,
      status,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EpisodeItem (
  val url: String,
  val name: String,
  val episodeNumber: Double,
  /** Epoch millis, 0 when the source did not say. */
  val dateUpload: Long,
  val scanlator: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EpisodeItem {
      val url = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val episodeNumber = pigeonVar_list[2] as Double
      val dateUpload = pigeonVar_list[3] as Long
      val scanlator = pigeonVar_list[4] as String?
      return EpisodeItem(url, name, episodeNumber, dateUpload, scanlator)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      name,
      episodeNumber,
      dateUpload,
      scanlator,
    )
  }
}

/**
 * One external track alongside a video.
 *
 * The language matters: a source commonly offers eight subtitle tracks and
 * the url alone gives the player no way to tell them apart, so an earlier
 * version of this bridge that carried only urls made the subtitle-language
 * preference unimplementable.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TrackItem (
  val url: String,
  /**
   * Whatever the source called it — a language name, a code, or empty.
   * Not normalised here; the host does not know the source's conventions.
   */
  val label: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrackItem {
      val url = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      return TrackItem(url, label)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      label,
    )
  }
}

/**
 * A playable stream. [headers] matters: many sources 403 without a Referer,
 * and section 8 requires passing them to the player.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VideoItem (
  val url: String,
  val videoUrl: String? = null,
  val quality: String,
  val headers: Map<String?, String?>,
  val subtitleTracks: List<TrackItem?>,
  val audioTracks: List<TrackItem?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoItem {
      val url = pigeonVar_list[0] as String
      val videoUrl = pigeonVar_list[1] as String?
      val quality = pigeonVar_list[2] as String
      val headers = pigeonVar_list[3] as Map<String?, String?>
      val subtitleTracks = pigeonVar_list[4] as List<TrackItem?>
      val audioTracks = pigeonVar_list[5] as List<TrackItem?>
      return VideoItem(url, videoUrl, quality, headers, subtitleTracks, audioTracks)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      videoUrl,
      quality,
      headers,
      subtitleTracks,
      audioTracks,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BrowseResult (
  val ok: Boolean,
  val sourceName: String,
  val items: List<AnimeItem?>,
  val hasNextPage: Boolean,
  val millis: Long,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BrowseResult {
      val ok = pigeonVar_list[0] as Boolean
      val sourceName = pigeonVar_list[1] as String
      val items = pigeonVar_list[2] as List<AnimeItem?>
      val hasNextPage = pigeonVar_list[3] as Boolean
      val millis = pigeonVar_list[4] as Long
      val error = pigeonVar_list[5] as String?
      return BrowseResult(ok, sourceName, items, hasNextPage, millis, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ok,
      sourceName,
      items,
      hasNextPage,
      millis,
      error,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DetailsResult (
  val ok: Boolean,
  val anime: AnimeItem? = null,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DetailsResult {
      val ok = pigeonVar_list[0] as Boolean
      val anime = pigeonVar_list[1] as AnimeItem?
      val error = pigeonVar_list[2] as String?
      return DetailsResult(ok, anime, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ok,
      anime,
      error,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EpisodesResult (
  val ok: Boolean,
  val items: List<EpisodeItem?>,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EpisodesResult {
      val ok = pigeonVar_list[0] as Boolean
      val items = pigeonVar_list[1] as List<EpisodeItem?>
      val error = pigeonVar_list[2] as String?
      return EpisodesResult(ok, items, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ok,
      items,
      error,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideosResult (
  val ok: Boolean,
  val items: List<VideoItem?>,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideosResult {
      val ok = pigeonVar_list[0] as Boolean
      val items = pigeonVar_list[1] as List<VideoItem?>
      val error = pigeonVar_list[2] as String?
      return VideosResult(ok, items, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ok,
      items,
      error,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadRequest (
  /**
   * Chosen by Dart so the record and the transfer share an identity even
   * before the host has seen it.
   */
  val id: String,
  val url: String,
  /** The source's headers. A download 403s without them just as playback does. */
  val headers: Map<String?, String?>,
  /** Without extension; the host appends one once it knows the format. */
  val fileName: String,
  /** Shown in the system notification. */
  val title: String,
  val subtitle: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadRequest {
      val id = pigeonVar_list[0] as String
      val url = pigeonVar_list[1] as String
      val headers = pigeonVar_list[2] as Map<String?, String?>
      val fileName = pigeonVar_list[3] as String
      val title = pigeonVar_list[4] as String
      val subtitle = pigeonVar_list[5] as String
      return DownloadRequest(id, url, headers, fileName, title, subtitle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      url,
      headers,
      fileName,
      title,
      subtitle,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadStatus (
  val id: String,
  val state: DownloadState,
  val bytesDownloaded: Long,
  /**
   * -1 when the server did not say, which is the common case for a playlist
   * assembled from segments.
   */
  val totalBytes: Long,
  val filePath: String? = null,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadStatus {
      val id = pigeonVar_list[0] as String
      val state = pigeonVar_list[1] as DownloadState
      val bytesDownloaded = pigeonVar_list[2] as Long
      val totalBytes = pigeonVar_list[3] as Long
      val filePath = pigeonVar_list[4] as String?
      val error = pigeonVar_list[5] as String?
      return DownloadStatus(id, state, bytesDownloaded, totalBytes, filePath, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      state,
      bytesDownloaded,
      totalBytes,
      filePath,
      error,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadAccepted (
  val accepted: Boolean,
  val refusal: DownloadRefusal
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadAccepted {
      val accepted = pigeonVar_list[0] as Boolean
      val refusal = pigeonVar_list[1] as DownloadRefusal
      return DownloadAccepted(accepted, refusal)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accepted,
      refusal,
    )
  }
}
private open class HostApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BrowseMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DownloadState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DownloadRefusal.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HostInfo.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExtensionCandidate.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FetchedAnime.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FetchResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApkInfo.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoadedSource.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ClassProbeResult.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnimeItem.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EpisodeItem.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrackItem.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoItem.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BrowseResult.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DetailsResult.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EpisodesResult.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideosResult.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadRequest.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadStatus.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadAccepted.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BrowseMode -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is DownloadState -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is DownloadRefusal -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is HostInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ExtensionCandidate -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is FetchedAnime -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is FetchResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is ApkInfo -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is LoadedSource -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ClassProbeResult -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is AnimeItem -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is EpisodeItem -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is TrackItem -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is VideoItem -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is BrowseResult -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is DetailsResult -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is EpisodesResult -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is VideosResult -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is DownloadRequest -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is DownloadStatus -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is DownloadAccepted -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ExtensionHostApi {
  fun getHostInfo(): HostInfo
  /**
   * Scans installed packages and returns any whose declared features or
   * metadata keys contain one of [needles] (case-insensitive).
   * Pass something like ["tachiyomi", "aniyomi", "extension"].
   */
  fun scanForExtensions(needles: List<String?>): List<ExtensionCandidate?>
  /**
   * Whether the user has granted "install unknown apps" for this app.
   * Checked live rather than cached: the user can revoke it at any time.
   */
  fun canInstallPackages(): Boolean
  /**
   * Opens the system settings page where that grant is made. Returns false
   * if no such screen could be launched.
   */
  fun openInstallPermissionSettings(): Boolean
  /**
   * What a successfully loaded source reports about itself. Proves the host
   * can talk to an extension through the shim, not merely construct it.
   */
  fun loadSources(packageName: String, classNames: List<String?>): List<LoadedSource?>
  /**
   * Calls a loaded source for real: one page of popular titles.
   *
   * Async because Pigeon dispatches host calls on the platform main
   * thread, and Android throws NetworkOnMainThreadException for network
   * work there. Confirmed the hard way.
   */
  fun fetchPopular(packageName: String, className: String, page: Long, callback: (Result<FetchResult>) -> Unit)
  /**
   * Performs a plain GET through the same OkHttp client extensions are
   * given. Distinguishes "the shim is broken" from "this device does not
   * trust that site" — the only question a TLS failure leaves open.
   */
  fun hostHttpCheck(url: String, callback: (Result<String>) -> Unit)
  /**
   * Reads an APK on disk without installing it: package, version, signing
   * key and manifest metadata. This is what the trust prompt is built from
   * (INSTRUCTIONS.md 5.5) — the key must be checked BEFORE install.
   */
  fun inspectApk(filePath: String): ApkInfo
  /**
   * Hands the APK to the system package installer. Returns false if no
   * installer could be launched. Android, not Mimasu, performs the install
   * and shows its own confirmation.
   */
  fun installApk(filePath: String): Boolean
  /** Launches the system uninstall prompt for an installed extension. */
  fun uninstallPackage(packageName: String): Boolean
  /**
   * Hosts an extension has contacted through the client the host provides.
   * Best-effort: an extension using its own client is not covered (5.7).
   */
  fun requestLogHostCounts(): Map<String?, Long?>
  /**
   * Builds a PathClassLoader over [packageName]'s APK and tries to load each
   * of [classNames], reporting ancestry and errors rather than throwing.
   */
  fun probeClasses(packageName: String, classNames: List<String?>): List<ClassProbeResult?>

  companion object {
    /** The codec used by ExtensionHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      HostApiPigeonCodec()
    }
    /** Sets up an instance of `ExtensionHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ExtensionHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.getHostInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getHostInfo())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.scanForExtensions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val needlesArg = args[0] as List<String?>
            val wrapped: List<Any?> = try {
              listOf(api.scanForExtensions(needlesArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.canInstallPackages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.canInstallPackages())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.openInstallPermissionSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.openInstallPermissionSettings())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.loadSources$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val classNamesArg = args[1] as List<String?>
            val wrapped: List<Any?> = try {
              listOf(api.loadSources(packageNameArg, classNamesArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.fetchPopular$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val classNameArg = args[1] as String
            val pageArg = args[2] as Long
            api.fetchPopular(packageNameArg, classNameArg, pageArg) { result: Result<FetchResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.hostHttpCheck$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.hostHttpCheck(urlArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.inspectApk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.inspectApk(filePathArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.installApk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.installApk(filePathArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.uninstallPackage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.uninstallPackage(packageNameArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.requestLogHostCounts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.requestLogHostCounts())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.ExtensionHostApi.probeClasses$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val classNamesArg = args[1] as List<String?>
            val wrapped: List<Any?> = try {
              listOf(api.probeClasses(packageNameArg, classNamesArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Browsing and playback through a loaded source.
 *
 * Every method is async: extension code performs network work, which Android
 * refuses on the platform thread that Pigeon dispatches host calls on.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface SourceApi {
  /** One page of titles. [query] is ignored unless [mode] is search. */
  fun browse(packageName: String, className: String, mode: BrowseMode, page: Long, query: String, callback: (Result<BrowseResult>) -> Unit)
  fun animeDetails(packageName: String, className: String, animeUrl: String, callback: (Result<DetailsResult>) -> Unit)
  fun episodes(packageName: String, className: String, animeUrl: String, callback: (Result<EpisodesResult>) -> Unit)
  fun videos(packageName: String, className: String, episodeUrl: String, callback: (Result<VideosResult>) -> Unit)
  /** Drops cached source instances, e.g. after an extension is updated. */
  fun clearSourceCache()

  companion object {
    /** The codec used by SourceApi. */
    val codec: MessageCodec<Any?> by lazy {
      HostApiPigeonCodec()
    }
    /** Sets up an instance of `SourceApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SourceApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.SourceApi.browse$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val classNameArg = args[1] as String
            val modeArg = args[2] as BrowseMode
            val pageArg = args[3] as Long
            val queryArg = args[4] as String
            api.browse(packageNameArg, classNameArg, modeArg, pageArg, queryArg) { result: Result<BrowseResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.SourceApi.animeDetails$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val classNameArg = args[1] as String
            val animeUrlArg = args[2] as String
            api.animeDetails(packageNameArg, classNameArg, animeUrlArg) { result: Result<DetailsResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.SourceApi.episodes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val classNameArg = args[1] as String
            val animeUrlArg = args[2] as String
            api.episodes(packageNameArg, classNameArg, animeUrlArg) { result: Result<EpisodesResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.SourceApi.videos$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val classNameArg = args[1] as String
            val episodeUrlArg = args[2] as String
            api.videos(packageNameArg, classNameArg, episodeUrlArg) { result: Result<VideosResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.SourceApi.clearSourceCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearSourceCache()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DownloadHostApi {
  /** Queues a transfer and starts the foreground service if it is not running. */
  fun enqueueDownload(request: DownloadRequest, wifiOnly: Boolean, callback: (Result<DownloadAccepted>) -> Unit)
  /**
   * Stops a transfer but keeps whatever was written, so the record can show
   * that it was cancelled rather than vanishing.
   */
  fun cancelDownload(id: String, callback: (Result<Unit>) -> Unit)
  /** Cancels if running, then deletes the file and forgets the transfer. */
  fun removeDownload(id: String, callback: (Result<Unit>) -> Unit)
  fun listDownloads(callback: (Result<List<DownloadStatus>>) -> Unit)
  /** Whether the active network is one the user pays for by the byte. */
  fun isMeteredConnection(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by DownloadHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      HostApiPigeonCodec()
    }
    /** Sets up an instance of `DownloadHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DownloadHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.DownloadHostApi.enqueueDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as DownloadRequest
            val wifiOnlyArg = args[1] as Boolean
            api.enqueueDownload(requestArg, wifiOnlyArg) { result: Result<DownloadAccepted> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.DownloadHostApi.cancelDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.cancelDownload(idArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.DownloadHostApi.removeDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.removeDownload(idArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.DownloadHostApi.listDownloads$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.listDownloads{ result: Result<List<DownloadStatus>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mimasu.DownloadHostApi.isMeteredConnection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isMeteredConnection{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
