// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// How the catalogue is being asked for.
enum BrowseMode {
  popular,
  latest,
  search,
}

/// What a download is doing. The host owns this, not Dart: a download outlives
/// the Flutter engine, so its state cannot live in a cubit.
enum DownloadState {
  queued,
  running,
  completed,
  failed,
  cancelled,
}

/// Why a download cannot be started right now. Distinguished from a failure
/// because nothing has gone wrong — the user asked at the wrong moment.
enum DownloadRefusal {
  none,
  metered,
  unsupportedFormat,
}

/// Basic environment facts, used to prove the channel round-trips before any
/// extension work is attempted.
class HostInfo {
  HostInfo({
    required this.androidRelease,
    required this.sdkInt,
    required this.hostPackage,
    required this.canRequestPackageInstalls,
  });

  String androidRelease;

  int sdkInt;

  String hostPackage;

  /// Whether the user has granted "install unknown apps" for this app.
  /// Extension installs (INSTRUCTIONS.md 5.4) are impossible until this is true.
  bool canRequestPackageInstalls;

  Object encode() {
    return <Object?>[
      androidRelease,
      sdkInt,
      hostPackage,
      canRequestPackageInstalls,
    ];
  }

  static HostInfo decode(Object result) {
    result as List<Object?>;
    return HostInfo(
      androidRelease: result[0]! as String,
      sdkInt: result[1]! as int,
      hostPackage: result[2]! as String,
      canRequestPackageInstalls: result[3]! as bool,
    );
  }
}

/// An installed package that looks like it might be a Tachiyomi-family
/// extension. Deliberately unopinionated: the scan does not assume a feature
/// name or metadata key, it reports whatever the package actually declares so
/// the real values can be read off a device instead of guessed.
class ExtensionCandidate {
  ExtensionCandidate({
    required this.packageName,
    required this.label,
    required this.versionName,
    required this.versionCode,
    required this.apkPath,
    required this.features,
    required this.metadata,
    required this.signatureSha256,
  });

  String packageName;

  String label;

  String versionName;

  int versionCode;

  /// Absolute path of the installed APK, the input to PathClassLoader.
  String apkPath;

  /// Every feature name the package declares in its manifest.
  List<String?> features;

  /// Every application-level manifest metadata entry, stringified.
  Map<String?, String?> metadata;

  /// SHA-256 of the signing certificate, uppercase hex, colon-separated.
  String signatureSha256;

  Object encode() {
    return <Object?>[
      packageName,
      label,
      versionName,
      versionCode,
      apkPath,
      features,
      metadata,
      signatureSha256,
    ];
  }

  static ExtensionCandidate decode(Object result) {
    result as List<Object?>;
    return ExtensionCandidate(
      packageName: result[0]! as String,
      label: result[1]! as String,
      versionName: result[2]! as String,
      versionCode: result[3]! as int,
      apkPath: result[4]! as String,
      features: (result[5] as List<Object?>?)!.cast<String?>(),
      metadata: (result[6] as Map<Object?, Object?>?)!.cast<String?, String?>(),
      signatureSha256: result[7]! as String,
    );
  }
}

/// One title as an extension reported it.
class FetchedAnime {
  FetchedAnime({
    required this.title,
    required this.url,
    this.thumbnailUrl,
    this.description,
  });

  String title;

  String url;

  String? thumbnailUrl;

  String? description;

  Object encode() {
    return <Object?>[
      title,
      url,
      thumbnailUrl,
      description,
    ];
  }

  static FetchedAnime decode(Object result) {
    result as List<Object?>;
    return FetchedAnime(
      title: result[0]! as String,
      url: result[1]! as String,
      thumbnailUrl: result[2] as String?,
      description: result[3] as String?,
    );
  }
}

/// The outcome of asking a source for a page of titles.
class FetchResult {
  FetchResult({
    required this.ok,
    required this.sourceName,
    required this.items,
    required this.hasNextPage,
    required this.millis,
    this.error,
  });

  bool ok;

  String sourceName;

  List<FetchedAnime?> items;

  bool hasNextPage;

  int millis;

  String? error;

  Object encode() {
    return <Object?>[
      ok,
      sourceName,
      items,
      hasNextPage,
      millis,
      error,
    ];
  }

  static FetchResult decode(Object result) {
    result as List<Object?>;
    return FetchResult(
      ok: result[0]! as bool,
      sourceName: result[1]! as String,
      items: (result[2] as List<Object?>?)!.cast<FetchedAnime?>(),
      hasNextPage: result[3]! as bool,
      millis: result[4]! as int,
      error: result[5] as String?,
    );
  }
}

/// What an APK on disk declares about itself, read before installing.
class ApkInfo {
  ApkInfo({
    required this.ok,
    required this.packageName,
    required this.label,
    required this.versionName,
    required this.versionCode,
    required this.signatureSha256,
    required this.features,
    required this.metadata,
    this.error,
  });

  bool ok;

  String packageName;

  String label;

  String versionName;

  int versionCode;

  /// Lowercase hex, no separators, so it compares directly against the key a
  /// repository index declares.
  String signatureSha256;

  List<String?> features;

  Map<String?, String?> metadata;

  String? error;

  Object encode() {
    return <Object?>[
      ok,
      packageName,
      label,
      versionName,
      versionCode,
      signatureSha256,
      features,
      metadata,
      error,
    ];
  }

  static ApkInfo decode(Object result) {
    result as List<Object?>;
    return ApkInfo(
      ok: result[0]! as bool,
      packageName: result[1]! as String,
      label: result[2]! as String,
      versionName: result[3]! as String,
      versionCode: result[4]! as int,
      signatureSha256: result[5]! as String,
      features: (result[6] as List<Object?>?)!.cast<String?>(),
      metadata: (result[7] as Map<Object?, Object?>?)!.cast<String?, String?>(),
      error: result[8] as String?,
    );
  }
}

/// A source instance the host managed to load, interrogated through the
/// shim interfaces.
class LoadedSource {
  LoadedSource({
    required this.className,
    required this.ok,
    required this.sourceId,
    required this.name,
    required this.lang,
    required this.baseUrl,
    required this.supportsLatest,
    required this.configurable,
    required this.filterCount,
    this.error,
  });

  String className;

  bool ok;

  /// 64-bit, so carried as a string.
  String sourceId;

  String name;

  String lang;

  String baseUrl;

  bool supportsLatest;

  bool configurable;

  /// How many filters the source declares for its search UI.
  int filterCount;

  String? error;

  Object encode() {
    return <Object?>[
      className,
      ok,
      sourceId,
      name,
      lang,
      baseUrl,
      supportsLatest,
      configurable,
      filterCount,
      error,
    ];
  }

  static LoadedSource decode(Object result) {
    result as List<Object?>;
    return LoadedSource(
      className: result[0]! as String,
      ok: result[1]! as bool,
      sourceId: result[2]! as String,
      name: result[3]! as String,
      lang: result[4]! as String,
      baseUrl: result[5]! as String,
      supportsLatest: result[6]! as bool,
      configurable: result[7]! as bool,
      filterCount: result[8]! as int,
      error: result[9] as String?,
    );
  }
}

/// The result of attempting to load one class out of an extension APK.
/// Failures are values, not exceptions (INSTRUCTIONS.md 5.8).
class ClassProbeResult {
  ClassProbeResult({
    required this.className,
    required this.loaded,
    required this.instantiated,
    required this.superclasses,
    this.error,
  });

  String className;

  /// Class.forName succeeded.
  bool loaded;

  /// A no-arg instance was constructed. Usually false until the
  /// extensions-lib shim is present.
  bool instantiated;

  /// The class's ancestry and interfaces, which is how we discover the exact
  /// extensions-lib type names an extension expects the host to provide.
  List<String?> superclasses;

  /// Null when nothing went wrong.
  String? error;

  Object encode() {
    return <Object?>[
      className,
      loaded,
      instantiated,
      superclasses,
      error,
    ];
  }

  static ClassProbeResult decode(Object result) {
    result as List<Object?>;
    return ClassProbeResult(
      className: result[0]! as String,
      loaded: result[1]! as bool,
      instantiated: result[2]! as bool,
      superclasses: (result[3] as List<Object?>?)!.cast<String?>(),
      error: result[4] as String?,
    );
  }
}

/// One title as a source reported it. Only what `SAnime` carries: there is no
/// metadata service underneath, so this is all the app will ever know.
class AnimeItem {
  AnimeItem({
    required this.url,
    required this.title,
    this.thumbnailUrl,
    this.description,
    this.author,
    this.genre,
    required this.status,
  });

  String url;

  String title;

  String? thumbnailUrl;

  String? description;

  String? author;

  String? genre;

  /// SAnime's status constants: 0 unknown, 1 ongoing, 2 completed, and so on.
  int status;

  Object encode() {
    return <Object?>[
      url,
      title,
      thumbnailUrl,
      description,
      author,
      genre,
      status,
    ];
  }

  static AnimeItem decode(Object result) {
    result as List<Object?>;
    return AnimeItem(
      url: result[0]! as String,
      title: result[1]! as String,
      thumbnailUrl: result[2] as String?,
      description: result[3] as String?,
      author: result[4] as String?,
      genre: result[5] as String?,
      status: result[6]! as int,
    );
  }
}

class EpisodeItem {
  EpisodeItem({
    required this.url,
    required this.name,
    required this.episodeNumber,
    required this.dateUpload,
    this.scanlator,
  });

  String url;

  String name;

  double episodeNumber;

  /// Epoch millis, 0 when the source did not say.
  int dateUpload;

  String? scanlator;

  Object encode() {
    return <Object?>[
      url,
      name,
      episodeNumber,
      dateUpload,
      scanlator,
    ];
  }

  static EpisodeItem decode(Object result) {
    result as List<Object?>;
    return EpisodeItem(
      url: result[0]! as String,
      name: result[1]! as String,
      episodeNumber: result[2]! as double,
      dateUpload: result[3]! as int,
      scanlator: result[4] as String?,
    );
  }
}

/// One external track alongside a video.
///
/// The language matters: a source commonly offers eight subtitle tracks and
/// the url alone gives the player no way to tell them apart, so an earlier
/// version of this bridge that carried only urls made the subtitle-language
/// preference unimplementable.
class TrackItem {
  TrackItem({
    required this.url,
    required this.label,
  });

  String url;

  /// Whatever the source called it — a language name, a code, or empty.
  /// Not normalised here; the host does not know the source's conventions.
  String label;

  Object encode() {
    return <Object?>[
      url,
      label,
    ];
  }

  static TrackItem decode(Object result) {
    result as List<Object?>;
    return TrackItem(
      url: result[0]! as String,
      label: result[1]! as String,
    );
  }
}

/// A playable stream. [headers] matters: many sources 403 without a Referer,
/// and section 8 requires passing them to the player.
class VideoItem {
  VideoItem({
    required this.url,
    this.videoUrl,
    required this.quality,
    required this.headers,
    required this.subtitleTracks,
    required this.audioTracks,
  });

  String url;

  String? videoUrl;

  String quality;

  Map<String?, String?> headers;

  List<TrackItem?> subtitleTracks;

  List<TrackItem?> audioTracks;

  Object encode() {
    return <Object?>[
      url,
      videoUrl,
      quality,
      headers,
      subtitleTracks,
      audioTracks,
    ];
  }

  static VideoItem decode(Object result) {
    result as List<Object?>;
    return VideoItem(
      url: result[0]! as String,
      videoUrl: result[1] as String?,
      quality: result[2]! as String,
      headers: (result[3] as Map<Object?, Object?>?)!.cast<String?, String?>(),
      subtitleTracks: (result[4] as List<Object?>?)!.cast<TrackItem?>(),
      audioTracks: (result[5] as List<Object?>?)!.cast<TrackItem?>(),
    );
  }
}

class BrowseResult {
  BrowseResult({
    required this.ok,
    required this.sourceName,
    required this.items,
    required this.hasNextPage,
    required this.millis,
    this.error,
  });

  bool ok;

  String sourceName;

  List<AnimeItem?> items;

  bool hasNextPage;

  int millis;

  String? error;

  Object encode() {
    return <Object?>[
      ok,
      sourceName,
      items,
      hasNextPage,
      millis,
      error,
    ];
  }

  static BrowseResult decode(Object result) {
    result as List<Object?>;
    return BrowseResult(
      ok: result[0]! as bool,
      sourceName: result[1]! as String,
      items: (result[2] as List<Object?>?)!.cast<AnimeItem?>(),
      hasNextPage: result[3]! as bool,
      millis: result[4]! as int,
      error: result[5] as String?,
    );
  }
}

class DetailsResult {
  DetailsResult({
    required this.ok,
    this.anime,
    this.error,
  });

  bool ok;

  AnimeItem? anime;

  String? error;

  Object encode() {
    return <Object?>[
      ok,
      anime,
      error,
    ];
  }

  static DetailsResult decode(Object result) {
    result as List<Object?>;
    return DetailsResult(
      ok: result[0]! as bool,
      anime: result[1] as AnimeItem?,
      error: result[2] as String?,
    );
  }
}

class EpisodesResult {
  EpisodesResult({
    required this.ok,
    required this.items,
    this.error,
  });

  bool ok;

  List<EpisodeItem?> items;

  String? error;

  Object encode() {
    return <Object?>[
      ok,
      items,
      error,
    ];
  }

  static EpisodesResult decode(Object result) {
    result as List<Object?>;
    return EpisodesResult(
      ok: result[0]! as bool,
      items: (result[1] as List<Object?>?)!.cast<EpisodeItem?>(),
      error: result[2] as String?,
    );
  }
}

class VideosResult {
  VideosResult({
    required this.ok,
    required this.items,
    this.error,
  });

  bool ok;

  List<VideoItem?> items;

  String? error;

  Object encode() {
    return <Object?>[
      ok,
      items,
      error,
    ];
  }

  static VideosResult decode(Object result) {
    result as List<Object?>;
    return VideosResult(
      ok: result[0]! as bool,
      items: (result[1] as List<Object?>?)!.cast<VideoItem?>(),
      error: result[2] as String?,
    );
  }
}

class DownloadRequest {
  DownloadRequest({
    required this.id,
    required this.url,
    required this.headers,
    required this.fileName,
    required this.title,
    required this.subtitle,
  });

  /// Chosen by Dart so the record and the transfer share an identity even
  /// before the host has seen it.
  String id;

  String url;

  /// The source's headers. A download 403s without them just as playback does.
  Map<String?, String?> headers;

  /// Without extension; the host appends one once it knows the format.
  String fileName;

  /// Shown in the system notification.
  String title;

  String subtitle;

  Object encode() {
    return <Object?>[
      id,
      url,
      headers,
      fileName,
      title,
      subtitle,
    ];
  }

  static DownloadRequest decode(Object result) {
    result as List<Object?>;
    return DownloadRequest(
      id: result[0]! as String,
      url: result[1]! as String,
      headers: (result[2] as Map<Object?, Object?>?)!.cast<String?, String?>(),
      fileName: result[3]! as String,
      title: result[4]! as String,
      subtitle: result[5]! as String,
    );
  }
}

class DownloadStatus {
  DownloadStatus({
    required this.id,
    required this.state,
    required this.bytesDownloaded,
    required this.totalBytes,
    this.filePath,
    this.error,
  });

  String id;

  DownloadState state;

  int bytesDownloaded;

  /// -1 when the server did not say, which is the common case for a playlist
  /// assembled from segments.
  int totalBytes;

  String? filePath;

  String? error;

  Object encode() {
    return <Object?>[
      id,
      state,
      bytesDownloaded,
      totalBytes,
      filePath,
      error,
    ];
  }

  static DownloadStatus decode(Object result) {
    result as List<Object?>;
    return DownloadStatus(
      id: result[0]! as String,
      state: result[1]! as DownloadState,
      bytesDownloaded: result[2]! as int,
      totalBytes: result[3]! as int,
      filePath: result[4] as String?,
      error: result[5] as String?,
    );
  }
}

class DownloadAccepted {
  DownloadAccepted({
    required this.accepted,
    required this.refusal,
  });

  bool accepted;

  DownloadRefusal refusal;

  Object encode() {
    return <Object?>[
      accepted,
      refusal,
    ];
  }

  static DownloadAccepted decode(Object result) {
    result as List<Object?>;
    return DownloadAccepted(
      accepted: result[0]! as bool,
      refusal: result[1]! as DownloadRefusal,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BrowseMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is DownloadState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is DownloadRefusal) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is HostInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is ExtensionCandidate) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is FetchedAnime) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is FetchResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is ApkInfo) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is LoadedSource) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is ClassProbeResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is AnimeItem) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is EpisodeItem) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is TrackItem) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is VideoItem) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is BrowseResult) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is DetailsResult) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is EpisodesResult) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is VideosResult) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is DownloadRequest) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is DownloadStatus) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is DownloadAccepted) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : BrowseMode.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DownloadState.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : DownloadRefusal.values[value];
      case 132: 
        return HostInfo.decode(readValue(buffer)!);
      case 133: 
        return ExtensionCandidate.decode(readValue(buffer)!);
      case 134: 
        return FetchedAnime.decode(readValue(buffer)!);
      case 135: 
        return FetchResult.decode(readValue(buffer)!);
      case 136: 
        return ApkInfo.decode(readValue(buffer)!);
      case 137: 
        return LoadedSource.decode(readValue(buffer)!);
      case 138: 
        return ClassProbeResult.decode(readValue(buffer)!);
      case 139: 
        return AnimeItem.decode(readValue(buffer)!);
      case 140: 
        return EpisodeItem.decode(readValue(buffer)!);
      case 141: 
        return TrackItem.decode(readValue(buffer)!);
      case 142: 
        return VideoItem.decode(readValue(buffer)!);
      case 143: 
        return BrowseResult.decode(readValue(buffer)!);
      case 144: 
        return DetailsResult.decode(readValue(buffer)!);
      case 145: 
        return EpisodesResult.decode(readValue(buffer)!);
      case 146: 
        return VideosResult.decode(readValue(buffer)!);
      case 147: 
        return DownloadRequest.decode(readValue(buffer)!);
      case 148: 
        return DownloadStatus.decode(readValue(buffer)!);
      case 149: 
        return DownloadAccepted.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ExtensionHostApi {
  /// Constructor for [ExtensionHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ExtensionHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<HostInfo> getHostInfo() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.getHostInfo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as HostInfo?)!;
    }
  }

  /// Scans installed packages and returns any whose declared features or
  /// metadata keys contain one of [needles] (case-insensitive).
  /// Pass something like ["tachiyomi", "aniyomi", "extension"].
  Future<List<ExtensionCandidate?>> scanForExtensions(List<String?> needles) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.scanForExtensions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[needles]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<ExtensionCandidate?>();
    }
  }

  /// Whether the user has granted "install unknown apps" for this app.
  /// Checked live rather than cached: the user can revoke it at any time.
  Future<bool> canInstallPackages() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.canInstallPackages$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Opens the system settings page where that grant is made. Returns false
  /// if no such screen could be launched.
  Future<bool> openInstallPermissionSettings() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.openInstallPermissionSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// What a successfully loaded source reports about itself. Proves the host
  /// can talk to an extension through the shim, not merely construct it.
  Future<List<LoadedSource?>> loadSources(String packageName, List<String?> classNames) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.loadSources$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageName, classNames]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<LoadedSource?>();
    }
  }

  /// Calls a loaded source for real: one page of popular titles.
  ///
  /// Async because Pigeon dispatches host calls on the platform main
  /// thread, and Android throws NetworkOnMainThreadException for network
  /// work there. Confirmed the hard way.
  Future<FetchResult> fetchPopular(String packageName, String className, int page) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.fetchPopular$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageName, className, page]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as FetchResult?)!;
    }
  }

  /// Performs a plain GET through the same OkHttp client extensions are
  /// given. Distinguishes "the shim is broken" from "this device does not
  /// trust that site" — the only question a TLS failure leaves open.
  Future<String> hostHttpCheck(String url) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.hostHttpCheck$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[url]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Reads an APK on disk without installing it: package, version, signing
  /// key and manifest metadata. This is what the trust prompt is built from
  /// (INSTRUCTIONS.md 5.5) — the key must be checked BEFORE install.
  Future<ApkInfo> inspectApk(String filePath) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.inspectApk$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[filePath]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ApkInfo?)!;
    }
  }

  /// Hands the APK to the system package installer. Returns false if no
  /// installer could be launched. Android, not Mimasu, performs the install
  /// and shows its own confirmation.
  Future<bool> installApk(String filePath) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.installApk$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[filePath]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Launches the system uninstall prompt for an installed extension.
  Future<bool> uninstallPackage(String packageName) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.uninstallPackage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageName]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Hosts an extension has contacted through the client the host provides.
  /// Best-effort: an extension using its own client is not covered (5.7).
  Future<Map<String?, int?>> requestLogHostCounts() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.requestLogHostCounts$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Map<Object?, Object?>?)!.cast<String?, int?>();
    }
  }

  /// Builds a PathClassLoader over [packageName]'s APK and tries to load each
  /// of [classNames], reporting ancestry and errors rather than throwing.
  Future<List<ClassProbeResult?>> probeClasses(String packageName, List<String?> classNames) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.probeClasses$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageName, classNames]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<ClassProbeResult?>();
    }
  }
}

/// Browsing and playback through a loaded source.
///
/// Every method is async: extension code performs network work, which Android
/// refuses on the platform thread that Pigeon dispatches host calls on.
class SourceApi {
  /// Constructor for [SourceApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SourceApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// One page of titles. [query] is ignored unless [mode] is search.
  Future<BrowseResult> browse(String packageName, String className, BrowseMode mode, int page, String query) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.SourceApi.browse$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageName, className, mode, page, query]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BrowseResult?)!;
    }
  }

  Future<DetailsResult> animeDetails(String packageName, String className, String animeUrl) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.SourceApi.animeDetails$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageName, className, animeUrl]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as DetailsResult?)!;
    }
  }

  Future<EpisodesResult> episodes(String packageName, String className, String animeUrl) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.SourceApi.episodes$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageName, className, animeUrl]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as EpisodesResult?)!;
    }
  }

  Future<VideosResult> videos(String packageName, String className, String episodeUrl) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.SourceApi.videos$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageName, className, episodeUrl]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as VideosResult?)!;
    }
  }

  /// Drops cached source instances, e.g. after an extension is updated.
  Future<void> clearSourceCache() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.SourceApi.clearSourceCache$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

class DownloadHostApi {
  /// Constructor for [DownloadHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DownloadHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Queues a transfer and starts the foreground service if it is not running.
  Future<DownloadAccepted> enqueueDownload(DownloadRequest request, bool wifiOnly) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.DownloadHostApi.enqueueDownload$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request, wifiOnly]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as DownloadAccepted?)!;
    }
  }

  /// Stops a transfer but keeps whatever was written, so the record can show
  /// that it was cancelled rather than vanishing.
  Future<void> cancelDownload(String id) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.DownloadHostApi.cancelDownload$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[id]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Cancels if running, then deletes the file and forgets the transfer.
  Future<void> removeDownload(String id) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.DownloadHostApi.removeDownload$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[id]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<DownloadStatus>> listDownloads() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.DownloadHostApi.listDownloads$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<DownloadStatus>();
    }
  }

  /// Whether the active network is one the user pays for by the byte.
  Future<bool> isMeteredConnection() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.DownloadHostApi.isMeteredConnection$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}
