// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Basic environment facts, used to prove the channel round-trips before any
/// extension work is attempted.
class HostInfo {
  HostInfo({
    required this.androidRelease,
    required this.sdkInt,
    required this.hostPackage,
    required this.canRequestPackageInstalls,
  });

  String androidRelease;

  int sdkInt;

  String hostPackage;

  /// Whether the user has granted "install unknown apps" for this app.
  /// Extension installs (INSTRUCTIONS.md 5.4) are impossible until this is true.
  bool canRequestPackageInstalls;

  Object encode() {
    return <Object?>[
      androidRelease,
      sdkInt,
      hostPackage,
      canRequestPackageInstalls,
    ];
  }

  static HostInfo decode(Object result) {
    result as List<Object?>;
    return HostInfo(
      androidRelease: result[0]! as String,
      sdkInt: result[1]! as int,
      hostPackage: result[2]! as String,
      canRequestPackageInstalls: result[3]! as bool,
    );
  }
}

/// An installed package that looks like it might be a Tachiyomi-family
/// extension. Deliberately unopinionated: the scan does not assume a feature
/// name or metadata key, it reports whatever the package actually declares so
/// the real values can be read off a device instead of guessed.
class ExtensionCandidate {
  ExtensionCandidate({
    required this.packageName,
    required this.label,
    required this.versionName,
    required this.versionCode,
    required this.apkPath,
    required this.features,
    required this.metadata,
    required this.signatureSha256,
  });

  String packageName;

  String label;

  String versionName;

  int versionCode;

  /// Absolute path of the installed APK, the input to PathClassLoader.
  String apkPath;

  /// Every feature name the package declares in its manifest.
  List<String?> features;

  /// Every application-level manifest metadata entry, stringified.
  Map<String?, String?> metadata;

  /// SHA-256 of the signing certificate, uppercase hex, colon-separated.
  String signatureSha256;

  Object encode() {
    return <Object?>[
      packageName,
      label,
      versionName,
      versionCode,
      apkPath,
      features,
      metadata,
      signatureSha256,
    ];
  }

  static ExtensionCandidate decode(Object result) {
    result as List<Object?>;
    return ExtensionCandidate(
      packageName: result[0]! as String,
      label: result[1]! as String,
      versionName: result[2]! as String,
      versionCode: result[3]! as int,
      apkPath: result[4]! as String,
      features: (result[5] as List<Object?>?)!.cast<String?>(),
      metadata: (result[6] as Map<Object?, Object?>?)!.cast<String?, String?>(),
      signatureSha256: result[7]! as String,
    );
  }
}

/// One title as an extension reported it.
class FetchedAnime {
  FetchedAnime({
    required this.title,
    required this.url,
    this.thumbnailUrl,
    this.description,
  });

  String title;

  String url;

  String? thumbnailUrl;

  String? description;

  Object encode() {
    return <Object?>[
      title,
      url,
      thumbnailUrl,
      description,
    ];
  }

  static FetchedAnime decode(Object result) {
    result as List<Object?>;
    return FetchedAnime(
      title: result[0]! as String,
      url: result[1]! as String,
      thumbnailUrl: result[2] as String?,
      description: result[3] as String?,
    );
  }
}

/// The outcome of asking a source for a page of titles.
class FetchResult {
  FetchResult({
    required this.ok,
    required this.sourceName,
    required this.items,
    required this.hasNextPage,
    required this.millis,
    this.error,
  });

  bool ok;

  String sourceName;

  List<FetchedAnime?> items;

  bool hasNextPage;

  int millis;

  String? error;

  Object encode() {
    return <Object?>[
      ok,
      sourceName,
      items,
      hasNextPage,
      millis,
      error,
    ];
  }

  static FetchResult decode(Object result) {
    result as List<Object?>;
    return FetchResult(
      ok: result[0]! as bool,
      sourceName: result[1]! as String,
      items: (result[2] as List<Object?>?)!.cast<FetchedAnime?>(),
      hasNextPage: result[3]! as bool,
      millis: result[4]! as int,
      error: result[5] as String?,
    );
  }
}

/// A source instance the host managed to load, interrogated through the
/// shim interfaces.
class LoadedSource {
  LoadedSource({
    required this.className,
    required this.ok,
    required this.sourceId,
    required this.name,
    required this.lang,
    required this.baseUrl,
    required this.supportsLatest,
    required this.configurable,
    required this.filterCount,
    this.error,
  });

  String className;

  bool ok;

  /// 64-bit, so carried as a string.
  String sourceId;

  String name;

  String lang;

  String baseUrl;

  bool supportsLatest;

  bool configurable;

  /// How many filters the source declares for its search UI.
  int filterCount;

  String? error;

  Object encode() {
    return <Object?>[
      className,
      ok,
      sourceId,
      name,
      lang,
      baseUrl,
      supportsLatest,
      configurable,
      filterCount,
      error,
    ];
  }

  static LoadedSource decode(Object result) {
    result as List<Object?>;
    return LoadedSource(
      className: result[0]! as String,
      ok: result[1]! as bool,
      sourceId: result[2]! as String,
      name: result[3]! as String,
      lang: result[4]! as String,
      baseUrl: result[5]! as String,
      supportsLatest: result[6]! as bool,
      configurable: result[7]! as bool,
      filterCount: result[8]! as int,
      error: result[9] as String?,
    );
  }
}

/// The result of attempting to load one class out of an extension APK.
/// Failures are values, not exceptions (INSTRUCTIONS.md 5.8).
class ClassProbeResult {
  ClassProbeResult({
    required this.className,
    required this.loaded,
    required this.instantiated,
    required this.superclasses,
    this.error,
  });

  String className;

  /// Class.forName succeeded.
  bool loaded;

  /// A no-arg instance was constructed. Usually false until the
  /// extensions-lib shim is present.
  bool instantiated;

  /// The class's ancestry and interfaces, which is how we discover the exact
  /// extensions-lib type names an extension expects the host to provide.
  List<String?> superclasses;

  /// Null when nothing went wrong.
  String? error;

  Object encode() {
    return <Object?>[
      className,
      loaded,
      instantiated,
      superclasses,
      error,
    ];
  }

  static ClassProbeResult decode(Object result) {
    result as List<Object?>;
    return ClassProbeResult(
      className: result[0]! as String,
      loaded: result[1]! as bool,
      instantiated: result[2]! as bool,
      superclasses: (result[3] as List<Object?>?)!.cast<String?>(),
      error: result[4] as String?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is HostInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ExtensionCandidate) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is FetchedAnime) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is FetchResult) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is LoadedSource) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is ClassProbeResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return HostInfo.decode(readValue(buffer)!);
      case 130: 
        return ExtensionCandidate.decode(readValue(buffer)!);
      case 131: 
        return FetchedAnime.decode(readValue(buffer)!);
      case 132: 
        return FetchResult.decode(readValue(buffer)!);
      case 133: 
        return LoadedSource.decode(readValue(buffer)!);
      case 134: 
        return ClassProbeResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ExtensionHostApi {
  /// Constructor for [ExtensionHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ExtensionHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<HostInfo> getHostInfo() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.getHostInfo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as HostInfo?)!;
    }
  }

  /// Scans installed packages and returns any whose declared features or
  /// metadata keys contain one of [needles] (case-insensitive).
  /// Pass something like ["tachiyomi", "aniyomi", "extension"].
  Future<List<ExtensionCandidate?>> scanForExtensions(List<String?> needles) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.scanForExtensions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[needles]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<ExtensionCandidate?>();
    }
  }

  /// Whether the user has granted "install unknown apps" for this app.
  /// Checked live rather than cached: the user can revoke it at any time.
  Future<bool> canInstallPackages() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.canInstallPackages$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Opens the system settings page where that grant is made. Returns false
  /// if no such screen could be launched.
  Future<bool> openInstallPermissionSettings() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.openInstallPermissionSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// What a successfully loaded source reports about itself. Proves the host
  /// can talk to an extension through the shim, not merely construct it.
  Future<List<LoadedSource?>> loadSources(String packageName, List<String?> classNames) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.loadSources$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageName, classNames]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<LoadedSource?>();
    }
  }

  /// Calls a loaded source for real: one page of popular titles.
  ///
  /// Async because Pigeon dispatches host calls on the platform main
  /// thread, and Android throws NetworkOnMainThreadException for network
  /// work there. Confirmed the hard way.
  Future<FetchResult> fetchPopular(String packageName, String className, int page) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.fetchPopular$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageName, className, page]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as FetchResult?)!;
    }
  }

  /// Performs a plain GET through the same OkHttp client extensions are
  /// given. Distinguishes "the shim is broken" from "this device does not
  /// trust that site" — the only question a TLS failure leaves open.
  Future<String> hostHttpCheck(String url) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.hostHttpCheck$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[url]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Hosts an extension has contacted through the client the host provides.
  /// Best-effort: an extension using its own client is not covered (5.7).
  Future<Map<String?, int?>> requestLogHostCounts() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.requestLogHostCounts$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Map<Object?, Object?>?)!.cast<String?, int?>();
    }
  }

  /// Builds a PathClassLoader over [packageName]'s APK and tries to load each
  /// of [classNames], reporting ancestry and errors rather than throwing.
  Future<List<ClassProbeResult?>> probeClasses(String packageName, List<String?> classNames) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.mimasu.ExtensionHostApi.probeClasses$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[packageName, classNames]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<ClassProbeResult?>();
    }
  }
}
